### ISSUE TITLE
일지 생성 뷰 Todo 사항

### ISSUE THREAD

**Issue by JEONG-J** [ttakkeun/Front_iOS#101]
## Issue: ✅ Todo
일지 생성 뷰에서 처리해야할 사항을 작성

## ✏️ Description
뷰 수정 및 API 연결 함수 등등 필요 사항 작성하기

## To-Do List
- [x] 일지 생성 시 답변 저장 서버에서 명세서 수정할 필요 있음
- [ ] 일지 생성 시 답변 관련 이미지 저장 API 작성 후, 답변 저장 후 reponse 받았을 경우 처리되도록 combine 처리
- [ ] 일지 생성 시, 답변 저장 및 사진 저장 질문 아이디 활용해서 넣을 것

## ETC
작성하고 꼭 1일 안으로 해결할 것
