### ISSUE TITLE
QnaTipsView Todo사항

### ISSUE THREAD

**Issue by sokft** [ttakkeun/Front_iOS#102]
## Issue: ✅ Todo
Todo 사항을 입력해주세요

## ✏️ Description
설명을 작성합니다

## To-Do List
- [x] #103
- [ ] 인기카테고리, 전체카테고리 다 API따로 만들고 받아와야함 > 그리고 하트버튼눌렀을때 success되면 뷰 다시 렌더링(필터는 내가하는게 아니다)
- [x] 이미지 여러개 받고 Tipcontent 수정하기
- [x] 초기화 제대로 하기 세그먼트이동, 하트버튼 누를때 등등
- [x] 지난시간 포맷팅 함수 수정
