### ISSUE TITLE
홈 뷰 수정

### ISSUE THREAD

**Issue by JEONG-J** [ttakkeun/Front_iOS#149]
## Issue: ✅ Todo
홈 뷰 리팩토링

## ✏️ Description
홈 뷰 추가 작업

## To-Do List
- [ ] 홈 뷰, 프로필 카드 API 연결
- [ ] 홈 뷰, Todo 그룹 API 연결
- [ ] 홈 뷰, AI상품 그럽 API 연결
