### ISSUE TITLE
API 문제 상황 정리

### ISSUE THREAD

**Issue by JEONG-J** [ttakkeun/Front_iOS#158]
## Issue: ✅ Todo
Todo 사항을 입력해주세요

## ✏️ Description
여러 상황의 API 테스트 시 발생하는 오류 작성

## To-Do List
- [x] 최근 진단 5개 받아오기 결과 값 오류 메시지 출력 문제 해결 필요. 데이터 없을 시 [] 배열로 되도록 하기
- [x] AI 진단 생성시, 귀를 제외한 부위 생성 안되는 거 해결 필요
- [x] 일지 검색 시, 페이징 없이 가능하도록 바꾸기
- [x] 실시간 검색 시, 정확도 문제 발생 이거 해결 필요

## ETC
1. 실시간 검색 시, "고양이" 왜 결과 데이터 없는가? ,"강아지" 왜 결과 데이터 없는거 검색 알고리즘 문제
