### ISSUE TITLE
7월 25일

### ISSUE THREAD

**Issue by JEONG-J** [ttakkeun/Front_iOS#35]
## Issue: ✅ Todo
Todo 사항을 입력해주세요

## ✏️ Description
설명을 작성합니다
홈 뷰 내부 UI와 ViewModel 완성하기
## To-Do List
- [ ] 홈뷰 프로필 카드 연결
- [ ] Todo 컴포넌트 API 연결 및 완료
- [ ] AI 추천 컴포넌트 API 연결 및 완료
- [ ] 유저 추천 제품 컴포넌트 API 연결 및 완료
