### ISSUE TITLE
7월 26일

### ISSUE THREAD

**Issue by sokft** [ttakkeun/Front_iOS#44]
## Issue: ✅ Todo
Todo 사항을 입력해주세요

## ✏️ Description
설명을 작성합니다

## To-Do List
- [x] Q&A뷰 분석 - 아래에 있는 테이블 뷰 같은 것은 어떻게 구성해야하는지,, 등 꼼꼼하게 분석완료하기
- [ ] 저번에 만들어진 로그인 뷰와 같은 예시를 통해 API연결 이해하기
- [x] 모르는 것 있으면 질문하기
