### ISSUE TITLE
7월 27일

### ISSUE THREAD

**Issue by JEONG-J** [ttakkeun/Front_iOS#47]
## Issue: ✅ Todo
Todo 사항을 입력해주세요
홈탭 내부 사용하는 반복 사용 컴포넌트 생성
## ✏️ Description
설명을 작성합니다

## To-Do List
- [x] 홈탭 내부 ToDo 카드 생성
- [x] Compact(2*2) Expand(1*4) 버전 Todo 카드 생성
- [ ] AI 추천 물품 카드 생성
- [ ] 유저 추천 물품 카드 생성
