### ISSUE TITLE
TODO 해야할 것!!!

### ISSUE THREAD

**Issue by alice0047** [ttakkeun/Front_iOS#79]
## Issue: ✅ Todo
Todo 사항을 입력해주세요

추가적으로 개발해야하는 사항들 정리 - 황유빈

## ✏️ Description
설명을 작성합니다

1. CustomDiary, CustomDiaryViewModel - 주차막대 출력에 필요한 코드 작성
2. CreateProfileViewModel(프로필 생성뷰 뷰모델) - API 연동 함수 필요함
3. CreateProfileView(프로필 생성뷰) - '등록하기' 버튼에 API 함수 액션 필요함
4. 온보딩뷰 API 연동 필요함

## To-Do List
- [ ] 할일 1. CustomDiary, CustomDiaryViewModel - 주차막대 출력에 필요한 코드 작성
- [ ] 할일 2. CreateProfileViewModel(프로필 생성뷰 뷰모델) - API 연동 함수 필요함
- [ ] 할일 3. CreateProfileView(프로필 생성뷰) - '등록하기' 버튼에 API 함수 액션 필요함
- [ ] 할일 4. 온보딩뷰 API 연동 필요함
